export const cityCode =
    {
        "UA": "Ukraine",
        "US": "United States",
        "RU": "Russia",
        "GB": "United Kingdom",
        "FR": "France",
        "DE": "Germany",
        "IT": "Italy",
        "ES": "Spain",
        "CN": "China",
        "JP": "Japan",
        "IN": "India",
        "BR": "Brazil",
        "CA": "Canada",
        "AU": "Australia",
        "MX": "Mexico",
        "AR": "Argentina",
        "ZA": "South Africa",
        "NG": "Nigeria",
        "KR": "South Korea",
        "SA": "Saudi Arabia",
        "TR": "Turkey",
        "EG": "Egypt",
        "SE": "Sweden",
        "NO": "Norway",
        "FI": "Finland",
        "PL": "Poland",
        "NL": "Netherlands",
        "BE": "Belgium",
        "CH": "Switzerland",
        "AT": "Austria",
        "DK": "Denmark",
        "PT": "Portugal",
        "GR": "Greece",
        "IL": "Israel",
        "TH": "Thailand",
        "MY": "Malaysia",
        "SG": "Singapore",
        "PH": "Philippines",
        "NZ": "New Zealand",
        "IE": "Ireland",
        "CZ": "Czech Republic",
        "HU": "Hungary",
        "RO": "Romania",
        "GT": "Guatemala",
        "CO": "Colombia"

    }

